parented_ptr: Cast to QObject to fix parent method signature mismatch
Classes inheriting from QAbstractItemModel are QObjects, but also have a
`parent()` method that takes a QModelIndex. In these cases, an error
like this may be thrown:

    src/util/parented_ptr.h: In instantiation of ‘parented_ptr<T>::~parented_ptr() [with T = TreeItemModel]’:
    src/library/itunes/itunesfeature.cpp:67:55:   required from here
    src/util/parented_ptr.h:31:45: error: no matching function for call to ‘TreeItemModel::parent()’
       31 |         DEBUG_ASSERT(!m_ptr || m_ptr->parent());
          |                                ~~~~~~~~~~~~~^~

This fixes the issue by casting to QObject first.