WPushButton: Use Qt::NoModifier instead of 0
    src/widget/wpushbutton.cpp: In member function ‘virtual bool WPushButton::event(QEvent*)’:
    src/widget/wpushbutton.cpp:453:59: error: ‘constexpr QFlags<T>::QFlags(QFlags<T>::Zero) [with Enum = Qt::KeyboardModifier; QFlags<T>::Zero = int QFlags<Qt::KeyboardModifier>::Private::*]’ is deprecated: Use default constructor instead [-Werror=deprecated-declarations]
      453 |                     Qt::MouseEventSynthesizedByApplication);
          |                                                           ^
    In file included from /usr/include/qt/QtCore/qglobal.h:1304,
                     from /usr/include/qt/QtGui/qtguiglobal.h:43,
                     from /usr/include/qt/QtGui/qevent.h:43,
                     from /usr/include/qt/QtGui/QPaintEvent:1,
                     from src/widget/wpushbutton.h:21,
                     from src/widget/wpushbutton.cpp:18:
    /usr/include/qt/QtCore/qflags.h:123:80: note: declared here
      123 |     QT_DEPRECATED_X("Use default constructor instead") Q_DECL_CONSTEXPR inline QFlags(Zero) noexcept : i(0) {}
          |