Fix integer expressions of different signedness
This patch fixes the following warning:

../src/effects/lv2/lv2effectprocessor.cpp: In member function 'virtual void LV2EffectProcessor::process(const ChannelHandle&, const ChannelHandle&, const CSAMPLE*, CSAMPLE*, const mixxx::EngineParameters&, EffectEnableState, const GroupFeatureState&)':
../src/effects/lv2/lv2effectprocessor.cpp:124:32: error: comparison of integer expressions of different signedness: 'unsigned int' and 'SINT' {aka 'int'} [-Werror=sign-compare]
  124 |     for (unsigned int i = 0; i < bufferParameters.samplesPerBuffer(); i += 2) {
      |                              ~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/effects/lv2/lv2effectprocessor.cpp:133:32: error: comparison of integer expressions of different signedness: 'unsigned int' and 'SINT' {aka 'int'} [-Werror=sign-compare]
  133 |     for (unsigned int i = 0; i < bufferParameters.samplesPerBuffer(); i += 2) {
      |                              ~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1plus: all warnings being treated as errors

As -Werror and -Werror=format-security are used during compilation theses are threated as errors.
Please notes that there is another occurence of this issue as:

But only -Werror=format-security is used, so it's not an error...

Signed-off-by: Nicolas Chauvet <kwizart@gmail.com>