fix(build): Fix `-Wdeprecated-declarations` warnings for `QDomDocument`
Fixes warnings such as:

    mixxx/src/skin/legacy/legacyskinparser.cpp: In static member function ‘static QDomE
    lement LegacySkinParser::openSkin(const QString&)’:
    mixxx/src/skin/legacy/legacyskinparser.cpp:237:25: error: ‘bool QDomDocument::setCo
    ntent(QIODevice*, QString*, int*, int*)’ is deprecated: Use the overload returning ParseResult instead
    . [-Werror=deprecated-declarations]
      237 |     if (!skin.setContent(&skinXmlFile,&errorMessage,&errorLine,&errorColumn)) {
          |          ~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    In file included from /usr/include/qt6/QtXml/QDomElement:1,
                     from mixxx/src/skin/legacy/legacyskinparser.h:3,
                     from mixxx/src/skin/legacy/legacyskinparser.cpp:1:
    /usr/include/qt6/QtXml/qdom.h:330:10: note: declared here
      330 |     bool setContent(QIODevice *dev, QString *errorMsg, int *errorLine = nullptr, int *errorCol
    umn = nullptr);
          |          ^~~~~~~~~~