explicitly convert QStrings to QFileInfos
required by Qt6
../src/controllers/dlgprefcontroller.cpp: In member function ‘virtual void DlgPrefController::slotApply()’:
../src/controllers/dlgprefcontroller.cpp:522:13: error: cannot convert ‘QString’ to ‘const QFileInfo&’
  522 |             mappingPath, QDir(resourceMappingsPath(m_pConfig)));
      |             ^~~~~~~~~~~
      |             |
      |             QString
In file included from ../src/controllers/hid/legacyhidcontrollermappingfilehandler.h:3,
                 from ../src/controllers/hid/legacyhidcontrollermapping.h:3,
                 from ../src/controllers/controllermappingtablemodel.h:10,
                 from ../src/controllers/controllerinputmappingtablemodel.h:8,
                 from ../src/controllers/dlgprefcontroller.h:7,
                 from ../src/controllers/dlgprefcontroller.cpp:1:
../src/controllers/legacycontrollermappingfilehandler.h:17:82: note:   initializing argument 1 of ‘static std::shared_ptr<LegacyControllerMapping> LegacyControllerMappingFileHandler::loadMapping(const QFileInfo&, const QDir&)’
   17 |     static std::shared_ptr<LegacyControllerMapping> loadMapping(const QFileInfo& mappingFile,
      |                                                                 ~~~~~~~~~~~~~~~~~^~~~~~~~~~~
../src/controllers/dlgprefcontroller.cpp: In member function ‘void DlgPrefController::slotMappingSelected(int)’:
../src/controllers/dlgprefcontroller.cpp:584:21: error: cannot convert ‘QString’ to ‘const QFileInfo&’
  584 |                     mappingPath, QDir(resourceMappingsPath(m_pConfig)));
      |                     ^~~~~~~~~~~
      |                     |
      |                     QString
In file included from ../src/controllers/hid/legacyhidcontrollermappingfilehandler.h:3,
                 from ../src/controllers/hid/legacyhidcontrollermapping.h:3,
                 from ../src/controllers/controllermappingtablemodel.h:10,
                 from ../src/controllers/controllerinputmappingtablemodel.h:8,
                 from ../src/controllers/dlgprefcontroller.h:7,
                 from ../src/controllers/dlgprefcontroller.cpp:1:
../src/controllers/legacycontrollermappingfilehandler.h:17:82: note:   initializing argument 1 of ‘static std::shared_ptr<LegacyControllerMapping> LegacyControllerMappingFileHandler::loadMapping(const QFileInfo&, const QDir&)’
   17 |     static std::shared_ptr<LegacyControllerMapping> loadMapping(const QFileInfo& mappingFile,
      |                                                                 ~~~~~~~~~~~~~~~~~^~~~~~~~~~~