soundsourceffmpeg: Fix Linux build
- Use getFilename() instead getLocalFileName() cause it's undefined in 1.12
Fix:
src/soundsourceffmpeg.cpp: In member function 'virtual Result SoundSourceFFmpeg::open()':
src/soundsourceffmpeg.cpp:397:51: error: 'getLocalFileName' was not declared in this scope
     const QByteArray qBAFilename(getLocalFileName().toLocal8Bit());

- Avoid double definition of "TagLib::MPEG::File f"
Fix:
src/soundsourceffmpeg.cpp:801:28: note: 'TagLib::MPEG::File f' previously declared here
         TagLib::MPEG::File f(qBAFilename.constData());