Replace recursive QMutexes with QRecursiveMutex
Recursive QMutexes have been deprecated since the 5.15.

Fixes warnings like these:

    src/vinylcontrol/vinylcontrolprocessor.cpp: In constructor ‘VinylControlProcessor::VinylControlProcessor(QObject*, UserSettingsPointer)’:
    src/vinylcontrol/vinylcontrolprocessor.cpp:28:32: error: ‘QMutex::QMutex(QMutex::RecursionMode)’ is deprecated: Use QRecursiveMutex instead of a recursive QMutex [-Werror=deprecated-declarations]
       28 |           m_bReloadConfig(false) {
          |                                ^
    In file included from /usr/include/qt/QtCore/QMutex:1,
                     from src/vinylcontrol/vinylcontrolprocessor.h:6,
                     from src/vinylcontrol/vinylcontrolprocessor.cpp:1:
    /usr/include/qt/QtCore/qmutex.h:140:14: note: declared here
      140 |     explicit QMutex(RecursionMode mode);
          |              ^~~~~~