track/cueinfoimporter: Add <memory> include for std::shared_ptr
Some compilers (e.g. on our OSX and Ubuntu 18.04 CI builds) fail when
this is missing:

    In file included from src/track/cueinfoimporter.cpp:1:0:
    src/track/cueinfoimporter.h:34:14: error: ‘shared_ptr’ in namespace ‘std’ does not name a template type
     typedef std::shared_ptr<CueInfoImporter> CueInfoImporterPointer;
                  ^~~~~~~~~~