fix controller mapping validation test
working around this error that happens when the Components
EffectUnit is initialized by the test:
ControllerEngine: Watching JS File: "E:/Jenkins/workspace/v2.1/mixxx-2.1-release/architecture/amd64/platform/windows/res/controllers/Reloop Terminal Mix 2-4.js"
ControllerEngine: Loading "E:/Jenkins/workspace/v2.1/mixxx-2.1-release/architecture/amd64/platform/windows/res/controllers/Reloop Terminal Mix 2-4.js"
ControlDoublePrivate::getControl returning NULL for ( "[EffectRack1_EffectUnit1]" , "show_parameters" )
"ControllerEngine: script tried to connect to ControlObject ([EffectRack1_EffectUnit1], show_parameters) which is non-existent, ignoring."
ControllerEngine: "Uncaught exception at line 666 in file E:/Jenkins/workspace/v2.1/mixxx-2.1-release/architecture/amd64/platform/windows/res/controllers/midi-components-0.0.js: TypeError: Result of expression 'this.showParametersConnection' [undefined] is not an object."
ControllerEngine shutting down...
src\test\controller_preset_validation_test.cpp(194): error: Value of: testLoadPreset(preset)
  Actual: false
Expected: true