EngineSyncTest: Fix double comparisons using EXPECT_NEAR
This fixes some issues on MSVC/Windows. The
EngineSyncTest.HalfDoubleThenPlay test fails on Appveyor (but not
gcc/clang on Linux). It looks like it's just some floating point
imprecision issue:

            Start 256: EngineSyncTest.HalfDoubleThenPlay
    256/628 Test #256: EngineSyncTest.HalfDoubleThenPlay ...............................................***Failed    1.09 sec
    Note: Google Test filter = EngineSyncTest.HalfDoubleThenPlay
    [==========] Running 1 test from 1 test case.
    [----------] Global test environment set-up.
    [----------] 1 test from EngineSyncTest
    [ RUN      ] EngineSyncTest.HalfDoubleThenPlay
    ..\src\test\enginesynctest.cpp(1574): error: Expected equality of these values:
      (m_pChannel1->getEngineBuffer()->m_pSyncControl->getBeatDistance())
        Which is: 0.067724867724867951
      (m_pChannel2->getEngineBuffer() ->m_pSyncControl->getBeatDistance())
        Which is: 0.067724867724867785
    ..\src\test\enginesynctest.cpp(1585): error: Expected equality of these values:
      (m_pChannel1->getEngineBuffer()->m_pSyncControl->getBeatDistance())
        Which is: 0.10158730158730181
      (m_pChannel2->getEngineBuffer() ->m_pSyncControl->getBeatDistance())
        Which is: 0.10158730158730164
    ..\src\test\enginesynctest.cpp(1593): error: Expected equality of these values:
      m_pChannel1->getEngineBuffer()->m_pSyncControl->getBeatDistance()
        Which is: 0.15238095238095259
      m_pChannel2->getEngineBuffer()->m_pSyncControl->getBeatDistance()
        Which is: 0.15238095238095245
    [  FAILED  ] EngineSyncTest.HalfDoubleThenPlay (946 ms)
    [----------] 1 test from EngineSyncTest (946 ms total)

    [----------] Global test environment tear-down
    [==========] 1 test from 1 test case ran. (946 ms total)
    [  PASSED  ] 0 tests.
    [  FAILED  ] 1 test, listed below:
    [  FAILED  ] EngineSyncTest.HalfDoubleThenPlay

     1 FAILED TEST

According to Owen Williams, the kMaxFloatingPointErrorHighPrecision
error suffices for this test.