CueControl: Fix cast from double to enum on MSVC
Fixes this error on MSVC:

    ..\src\engine\controls\cuecontrol.cpp(2478): error C2440: 'static_cast': cannot convert from 'double' to 'HotcueControl::Status'
    ..\src\engine\controls\cuecontrol.cpp(2478): note: Conversions between enumeration and floating point values are no longer allowed