fix: Use `!isEmpty()` instead of using `count()` as bool
Fixes warnings like these:

    src/engine/enginemixer.cpp:509:47: error: use isEmpty() instead [-Wclazy-isempty-vs-count]
            m_pTalkoverDucking->setAboveThreshold(m_activeTalkoverChannels.size());
                                                  ^